spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://192.168.10.107:3306/workflow?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
  thymeleaf:
    cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
